// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The certificate issuer list result.
    /// </summary>
    public partial class CertificateIssuerListResult
    {
        /// <summary>
        /// Initializes a new instance of the CertificateIssuerListResult
        /// class.
        /// </summary>
        public CertificateIssuerListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CertificateIssuerListResult
        /// class.
        /// </summary>
        /// <param name="value">A response message containing a list of
        /// certificate issuers in the key vault along with a link to the next
        /// page of certificate issuers.</param>
        /// <param name="nextLink">The URL to get the next set of certificate
        /// issuers.</param>
        public CertificateIssuerListResult(IList<CertificateIssuerItem> value = default(IList<CertificateIssuerItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of certificate issuers in
        /// the key vault along with a link to the next page of certificate
        /// issuers.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<CertificateIssuerItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of certificate issuers.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
