// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The certificate issuer item containing certificate issuer metadata.
    /// </summary>
    public partial class CertificateIssuerItem
    {
        /// <summary>
        /// Initializes a new instance of the CertificateIssuerItem class.
        /// </summary>
        public CertificateIssuerItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CertificateIssuerItem class.
        /// </summary>
        /// <param name="id">Certificate Identifier.</param>
        /// <param name="provider">The issuer provider.</param>
        public CertificateIssuerItem(string id = default(string), string provider = default(string))
        {
            Id = id;
            Provider = provider;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets certificate Identifier.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the issuer provider.
        /// </summary>
        [JsonProperty(PropertyName = "provider")]
        public string Provider { get; set; }

    }
}
