// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The certificate list result.
    /// </summary>
    public partial class CertificateListResult
    {
        /// <summary>
        /// Initializes a new instance of the CertificateListResult class.
        /// </summary>
        public CertificateListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CertificateListResult class.
        /// </summary>
        /// <param name="value">A response message containing a list of
        /// certificates in the key vault along with a link to the next page of
        /// certificates.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// certificates.</param>
        public CertificateListResult(IList<CertificateItem> value = default(IList<CertificateItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of certificates in the
        /// key vault along with a link to the next page of certificates.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<CertificateItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of certificates.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
