// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The deleted secret list result
    /// </summary>
    public partial class DeletedSecretListResult
    {
        /// <summary>
        /// Initializes a new instance of the DeletedSecretListResult class.
        /// </summary>
        public DeletedSecretListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeletedSecretListResult class.
        /// </summary>
        /// <param name="value">A response message containing a list of the
        /// deleted secrets in the vault along with a link to the next page of
        /// deleted secrets</param>
        /// <param name="nextLink">The URL to get the next set of deleted
        /// secrets.</param>
        public DeletedSecretListResult(IList<DeletedSecretItem> value = default(IList<DeletedSecretItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of the deleted secrets in
        /// the vault along with a link to the next page of deleted secrets
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DeletedSecretItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of deleted secrets.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
