// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The deleted storage account list result
    /// </summary>
    public partial class DeletedStorageListResult
    {
        /// <summary>
        /// Initializes a new instance of the DeletedStorageListResult class.
        /// </summary>
        public DeletedStorageListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeletedStorageListResult class.
        /// </summary>
        /// <param name="value">A response message containing a list of the
        /// deleted storage accounts in the vault along with a link to the next
        /// page of deleted storage accounts</param>
        /// <param name="nextLink">The URL to get the next set of deleted
        /// storage accounts.</param>
        public DeletedStorageListResult(IList<DeletedStorageAccountItem> value = default(IList<DeletedStorageAccountItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of the deleted storage
        /// accounts in the vault along with a link to the next page of deleted
        /// storage accounts
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DeletedStorageAccountItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of deleted storage accounts.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
