// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A list of certificates that have been deleted in this vault.
    /// </summary>
    public partial class DeletedCertificateListResult
    {
        /// <summary>
        /// Initializes a new instance of the DeletedCertificateListResult
        /// class.
        /// </summary>
        public DeletedCertificateListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeletedCertificateListResult
        /// class.
        /// </summary>
        /// <param name="value">A response message containing a list of deleted
        /// certificates in the vault along with a link to the next page of
        /// deleted certificates</param>
        /// <param name="nextLink">The URL to get the next set of deleted
        /// certificates.</param>
        public DeletedCertificateListResult(IList<DeletedCertificateItem> value = default(IList<DeletedCertificateItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of deleted certificates
        /// in the vault along with a link to the next page of deleted
        /// certificates
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DeletedCertificateItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of deleted certificates.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
