// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The deleted SAS definition list result
    /// </summary>
    public partial class DeletedSasDefinitionListResult
    {
        /// <summary>
        /// Initializes a new instance of the DeletedSasDefinitionListResult
        /// class.
        /// </summary>
        public DeletedSasDefinitionListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeletedSasDefinitionListResult
        /// class.
        /// </summary>
        /// <param name="value">A response message containing a list of the
        /// deleted SAS definitions in the vault along with a link to the next
        /// page of deleted sas definitions</param>
        /// <param name="nextLink">The URL to get the next set of deleted SAS
        /// definitions.</param>
        public DeletedSasDefinitionListResult(IList<DeletedSasDefinitionItem> value = default(IList<DeletedSasDefinitionItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of the deleted SAS
        /// definitions in the vault along with a link to the next page of
        /// deleted sas definitions
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DeletedSasDefinitionItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of deleted SAS definitions.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
