// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for JsonWebKeySignatureAlgorithm.
    /// </summary>
    public static class JsonWebKeySignatureAlgorithm
    {
        /// <summary>
        /// RSASSA-PSS using SHA-256 and MGF1 with SHA-256, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string PS256 = "PS256";
        /// <summary>
        /// RSASSA-PSS using SHA-384 and MGF1 with SHA-384, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string PS384 = "PS384";
        /// <summary>
        /// RSASSA-PSS using SHA-512 and MGF1 with SHA-512, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string PS512 = "PS512";
        /// <summary>
        /// RSASSA-PKCS1-v1_5 using SHA-256, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string RS256 = "RS256";
        /// <summary>
        /// RSASSA-PKCS1-v1_5 using SHA-384, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string RS384 = "RS384";
        /// <summary>
        /// RSASSA-PKCS1-v1_5 using SHA-512, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string RS512 = "RS512";
        /// <summary>
        /// Reserved
        /// </summary>
        public const string RSNULL = "RSNULL";
        /// <summary>
        /// ECDSA using P-256 and SHA-256, as described in
        /// https://tools.ietf.org/html/rfc7518.
        /// </summary>
        public const string ES256 = "ES256";
        /// <summary>
        /// ECDSA using P-384 and SHA-384, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string ES384 = "ES384";
        /// <summary>
        /// ECDSA using P-521 and SHA-512, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string ES512 = "ES512";
        /// <summary>
        /// ECDSA using P-256K and SHA-256, as described in
        /// https://tools.ietf.org/html/rfc7518
        /// </summary>
        public const string ES256K = "ES256K";
    }
}
