// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for JsonWebKeyOperation.
    /// </summary>
    public static class JsonWebKeyOperation
    {
        public const string Encrypt = "encrypt";
        public const string Decrypt = "decrypt";
        public const string Sign = "sign";
        public const string Verify = "verify";
        public const string WrapKey = "wrapKey";
        public const string UnwrapKey = "unwrapKey";
    }
}
