// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for JsonWebKeyEncryptionAlgorithm.
    /// </summary>
    public static class JsonWebKeyEncryptionAlgorithm
    {
        public const string RSAOAEP = "RSA-OAEP";
        public const string RSAOAEP256 = "RSA-OAEP-256";
        public const string RSA15 = "RSA1_5";
    }
}
