// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for JsonWebKeyType.
    /// </summary>
    public static class JsonWebKeyType
    {
        /// <summary>
        /// Elliptic Curve.
        /// </summary>
        public const string EC = "EC";
        /// <summary>
        /// Elliptic Curve with a private key which is not exportable from the
        /// HSM.
        /// </summary>
        public const string ECHSM = "EC-HSM";
        /// <summary>
        /// RSA (https://tools.ietf.org/html/rfc3447)
        /// </summary>
        public const string RSA = "RSA";
        /// <summary>
        /// RSA with a private key which is not exportable from the HSM.
        /// </summary>
        public const string RSAHSM = "RSA-HSM";
        /// <summary>
        /// Not supported in this version. Octet sequence (used to represent
        /// symmetric keys)
        /// </summary>
        public const string Oct = "oct";
    }
}
