// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for JsonWebKeyCurveName.
    /// </summary>
    public static class JsonWebKeyCurveName
    {
        /// <summary>
        /// The NIST P-256 elliptic curve, AKA SECG curve SECP256R1.
        /// </summary>
        public const string P256 = "P-256";
        /// <summary>
        /// The NIST P-384 elliptic curve, AKA SECG curve SECP384R1.
        /// </summary>
        public const string P384 = "P-384";
        /// <summary>
        /// The NIST P-521 elliptic curve, AKA SECG curve SECP521R1.
        /// </summary>
        public const string P521 = "P-521";
        /// <summary>
        /// The SECG SECP256K1 elliptic curve.
        /// </summary>
        public const string P256K = "P-256K";
    }
}
