// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The key list result.
    /// </summary>
    public partial class KeyListResult
    {
        /// <summary>
        /// Initializes a new instance of the KeyListResult class.
        /// </summary>
        public KeyListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KeyListResult class.
        /// </summary>
        /// <param name="value">A response message containing a list of keys in
        /// the key vault along with a link to the next page of keys.</param>
        /// <param name="nextLink">The URL to get the next set of keys.</param>
        public KeyListResult(IList<KeyItem> value = default(IList<KeyItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of keys in the key vault
        /// along with a link to the next page of keys.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<KeyItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of keys.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
