// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for KeyUsageType.
    /// </summary>
    public static class KeyUsageType
    {
        public const string DigitalSignature = "digitalSignature";
        public const string NonRepudiation = "nonRepudiation";
        public const string KeyEncipherment = "keyEncipherment";
        public const string DataEncipherment = "dataEncipherment";
        public const string KeyAgreement = "keyAgreement";
        public const string KeyCertSign = "keyCertSign";
        public const string CRLSign = "cRLSign";
        public const string EncipherOnly = "encipherOnly";
        public const string DecipherOnly = "decipherOnly";
    }
}
