// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The pending certificate signing request result.
    /// </summary>
    public partial class PendingCertificateSigningRequestResult
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PendingCertificateSigningRequestResult class.
        /// </summary>
        public PendingCertificateSigningRequestResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PendingCertificateSigningRequestResult class.
        /// </summary>
        /// <param name="value">The pending certificate signing request as
        /// Base64 encoded string.</param>
        public PendingCertificateSigningRequestResult(string value = default(string))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the pending certificate signing request as Base64 encoded
        /// string.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; private set; }

    }
}
