// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The storage account SAS definition list result.
    /// </summary>
    public partial class SasDefinitionListResult
    {
        /// <summary>
        /// Initializes a new instance of the SasDefinitionListResult class.
        /// </summary>
        public SasDefinitionListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SasDefinitionListResult class.
        /// </summary>
        /// <param name="value">A response message containing a list of SAS
        /// definitions along with a link to the next page of SAS
        /// definitions.</param>
        /// <param name="nextLink">The URL to get the next set of SAS
        /// definitions.</param>
        public SasDefinitionListResult(IList<SasDefinitionItem> value = default(IList<SasDefinitionItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of SAS definitions along
        /// with a link to the next page of SAS definitions.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<SasDefinitionItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of SAS definitions.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
