// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{

    /// <summary>
    /// Defines values for SasTokenType.
    /// </summary>
    public static class SasTokenType
    {
        public const string Account = "account";
        public const string Service = "service";
    }
}
