// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AzureKeyVaultEmulator.V7.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The storage accounts list result.
    /// </summary>
    public partial class StorageListResult
    {
        /// <summary>
        /// Initializes a new instance of the StorageListResult class.
        /// </summary>
        public StorageListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StorageListResult class.
        /// </summary>
        /// <param name="value">A response message containing a list of storage
        /// accounts in the key vault along with a link to the next page of
        /// storage accounts.</param>
        /// <param name="nextLink">The URL to get the next set of storage
        /// accounts.</param>
        public StorageListResult(IList<StorageAccountItem> value = default(IList<StorageAccountItem>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a response message containing a list of storage accounts in
        /// the key vault along with a link to the next page of storage
        /// accounts.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<StorageAccountItem> Value { get; private set; }

        /// <summary>
        /// Gets the URL to get the next set of storage accounts.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
